project:
  output-dir: docs
  render:
    - "*.qmd"
    - "!00_archive/"
  resources:
    - "img/"
    - "code/"
    - "reveal.js-master/"
    - "module1.html"



format:
  revealjs:
    embed-resources: false
