---
title: Staff's page
author: Diogo Silva
format:
  html:
    embed-resources: true
---

# Links

- [Github repository](https://github.com/diogo-aos/iseg_pg_aaiml_intro_python)
- Slides
  - [Module 1](module1.html)
  - [Module 1 recap](lectures/2_aula1_recap.html)
  - [Module 2](lectures/3_aula2.html)
  - [Module 2 recap](lectures/4_aula2_recap.html)
  - [Module 3](lectures/5_lesson3.html)
  - [Module 3 recap](lectures/6_lesson3_recap.html)
  - [Module 4](lectures/7_lesson4.html)
- [Exercises](exercises.html)
- [Debug demo guide](lesson4_debug_demo_guide.html)


# Lesson plan 2025-10-13

- Lecture 1 recap
- [Exercise 1](exercises.qmd#exercise-1)
- Slides
- [Exercise 3](exercises.qmd#exercise-3)


# Lesson plan 2025-10-20

- Recap until module 4 (excluding packages) ([Recap 2](lectures/4_aula2_recap.qmd), [Recap 3](lectures/6_lesson3_recap.qmd))
- Exceptions, traceback (Slides)
- Exercise walk-through - Boston House Prices
  - Exceptions demo
- Packages demo: legacy, [Boston](packages_guide_boston.qmd)
- Classes (Slides)
- Debugging - 4 different ways
- [Debugging demo](lesson4_debug_demo_guide.qmd)

# Checklist for lectures 

- Setup
  - Open development environment for demo and walkthrough
  - Open slides
  - Open Teams window
  - Test camera
  - Test microphone
  - Count number of students in class
- During lecture
  - Count people
  - Ask permission to record
  - Record
  - Ask permission again while recording (to have it on the record)

