---
title: Module 1 Recap
format: revealjs
---

# Module 1 Recap

---

### Topics

- Setup development environment
- Create and use a Jupyter Notebook
- Create variables
- Input/output information: ``print`` and ``input``

---

- Numeric types: int vs float, operations
- Strings:
  - `"a string"` and ``'also a string'``
  - concatenation, formatting `f"pi={3.1415}"`
- Boolean type: ``True`` and ``False``
- Type conversion, e.g. ``float("3.14")``
- Making decisions: ``if / elif / else``
- Conditions: basics, boolean logic
- ``and   or`` vs. ``&   |``

---

- ``pip install`` packages
- ``import`` packages to our programs, e.g. ``import pandas``

---

- Practical example
  - Load tabular data from Excel file
  - Learn about relative vs. absolute paths
  - Create masks with boolean logic to filter table


---

### Learning outcomes - you now can:

- setup a development environment with Jupyter
- store and load data of different types in variables
- retrieve and display information
- convert data between types
- perform operations with numeric types
- format a string

---

- make decisions based on conditions
- install a Python package
- import a package and use its functions
- load data from an Excel file
- basic data filtering using boolean logic


# {background-image="../img/apresentacoes_Python_end.png" background-size="contain" background-repeat="no-repeat"}
